name: cumrid_story_editor
description: "This package uses style of WhatsApp story image/video editor, you can edit images and videos. You can add texts, stickers, finger drawing, apply filter, and undo"
version: 0.0.2

license: MIT


repository: https://github.com/AdnanKhan45/cumrid_story_editor/tree/main
homepage: https://github.com/AdnanKhan45/cumrid_story_editor/blob/main/lib/cumrid_story_editor.dart

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_cropper: ^9.1.0
  video_player: ^2.8.6
  video_trimmer: ^3.0.0
  video_thumbnail: ^0.5.3
  hsv_color_pickers: ^0.4.0
  perfect_freehand: ^2.3.2
  

  file_picker: ^10.1.9
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_keyboard_visibility: ^6.0.0
  vector_math: ^2.1.4
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296

dependency_overrides: 
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/
    - assets/emojies/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf
    - family: Mandimi One
      fonts:
        - asset: assets/fonts/madimiOne/MadimiOne-Regular.ttf
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/dancing_script/DancingScript-Regular.ttf
    - family: Angkor
      fonts:
        - asset: assets/fonts/angkor/Angkor-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/oswald/Oswald-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/Pacifico-Regular.ttf
 
